//! Endpoint — IEndpoint implementations for dual-mode dispatch.

use lrdi::ServiceProvider;
use lrwf_core::auth::IAuthorizationPolicy;
use lrwf_core::error::Result;
use lrwf_core::http::IHttpContext;
use lrwf_core::routing::IEndpoint;
use serde_json;
use std::sync::Arc;

/// Endpoint that wraps a boxed async handler.
#[allow(clippy::type_complexity)]
pub struct RequestEndpoint {
    handler: Box<
        dyn Fn(
                &mut dyn IHttpContext,
            )
                -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send + '_>>
            + Send
            + Sync,
    >,
}

#[async_trait::async_trait]
impl IEndpoint for RequestEndpoint {
    async fn handle(&self, ctx: &mut dyn IHttpContext) -> Result<()> {
        (self.handler)(ctx).await
    }
}

impl RequestEndpoint {
    pub fn new<F>(f: F) -> Self
    where
        F: for<'a> Fn(
                &'a mut dyn IHttpContext,
            ) -> std::pin::Pin<
                Box<dyn std::future::Future<Output = Result<()>> + Send + 'a>,
            > + Send
            + Sync
            + 'static,
    {
        Self {
            handler: Box::new(f),
        }
    }
}

/// A route endpoint that dispatches to the registered handler via the mediator.
///
/// When a dispatch function is available (generated by the endpoint macros),
/// it constructs the request from the HTTP request data, calls the mediator,
/// and writes the JSON response. Falls back to a descriptive stub message
/// when no dispatch function is registered.
#[allow(clippy::type_complexity)]
pub struct StubEndpoint {
    pub method: &'static str,
    pub path: &'static str,
    pub handler_type: &'static str,
    pub dispatch_fn: Option<
        fn(
            Vec<u8>,
            std::collections::HashMap<String, String>,
            std::collections::HashMap<String, String>,
            Arc<ServiceProvider>,
            Option<Box<dyn lrwf_core::auth::IClaims>>,
        ) -> std::pin::Pin<
            Box<dyn std::future::Future<Output = Result<lrwf_core::di::scan::ResponseData>> + Send>,
        >,
    >,
    pub provider: Option<Arc<ServiceProvider>>,
    pub auth_required_role: &'static str,
    /// Dynamic authorization policy (from `IAuthorizationPolicy`).
    /// Checked after static `#[authorize]` and before handler dispatch.
    pub policy: Option<Arc<dyn IAuthorizationPolicy>>,
}

#[async_trait::async_trait]
impl IEndpoint for StubEndpoint {
    async fn handle(&self, ctx: &mut dyn IHttpContext) -> Result<()> {
        if let (Some(dispatch), Some(ref provider)) = (self.dispatch_fn, &self.provider) {
            let body_bytes = ctx.request().body_bytes().await.unwrap_or_default();
            let route_params = ctx.request().route_params().clone();
            let query_params = ctx.request().query().clone();

            // Extract claims from the context so they can be forwarded explicitly
            // to the handler via the dispatch function (fearless concurrency).
            let claims = ctx.claims().map(|c| c.clone_box());

            // ── Authorization check (declared on route via #[authorize]) ──
            if !self.auth_required_role.is_empty() {
                match ctx.claims() {
                    None => {
                        // No authenticated user at all
                        ctx.response_mut().set_status(401);
                        ctx.response_mut()
                            .set_header("content-type", "application/json");
                        ctx.response_mut()
                            .write_bytes(
                                serde_json::to_vec(&serde_json::json!({
                                    "error": "Authentication required",
                                    "status": 401
                                }))
                                .unwrap_or_default(),
                            )
                            .await?;
                        return Ok(());
                    }
                    Some(claims) => {
                        if self.auth_required_role != "authenticated"
                            && !claims
                                .roles()
                                .iter()
                                .any(|r| r.as_str() == self.auth_required_role)
                        {
                            ctx.response_mut().set_status(403);
                            ctx.response_mut()
                                .set_header("content-type", "application/json");
                            ctx.response_mut()
                                .write_bytes(
                                    serde_json::to_vec(&serde_json::json!({
                                        "error": "Forbidden: insufficient permissions",
                                        "status": 403,
                                        "required_role": self.auth_required_role,
                                    }))
                                    .unwrap_or_default(),
                                )
                                .await?;
                            return Ok(());
                        }
                    }
                }
            }

            // ── Dynamic authorization policy check (IAuthorizationPolicy) ──
            // Only runs when the route is protected by #[authorize].
            // Available AFTER routing (route_pattern is set by the router).
            if !self.auth_required_role.is_empty() {
                if let Some(ref policy) = self.policy {
                    if let Some(claims) = ctx.claims() {
                        let resource_key = ctx.request().route_pattern().unwrap_or(self.path);
                        let method = ctx.request().method();
                        policy.authorize(claims, resource_key, method).await?;
                    }
                }
            }

            let response = dispatch(
                body_bytes,
                route_params,
                query_params,
                Arc::clone(provider),
                claims,
            )
            .await?;

            ctx.response_mut().set_status(response.status);
            ctx.response_mut()
                .set_header("content-type", &response.content_type);
            ctx.response_mut().write_bytes(response.body).await?;
            return Ok(());
        }

        // Fallback: stub message (when no dispatch function is registered)
        ctx.response_mut().set_status(200);
        ctx.response_mut()
            .write_text(&format!(
                "Matched route: {} {} (handler: {})",
                self.method, self.path, self.handler_type
            ))
            .await?;
        Ok(())
    }
}

/// Endpoint for controller-based methods.
#[allow(clippy::type_complexity)]
pub struct ControllerEndpoint {
    handler: Box<
        dyn Fn(
                &mut dyn IHttpContext,
            )
                -> std::pin::Pin<Box<dyn std::future::Future<Output = Result<()>> + Send + '_>>
            + Send
            + Sync,
    >,
}

#[async_trait::async_trait]
impl IEndpoint for ControllerEndpoint {
    async fn handle(&self, ctx: &mut dyn IHttpContext) -> Result<()> {
        (self.handler)(ctx).await
    }
}

impl ControllerEndpoint {
    pub fn new<F>(f: F) -> Self
    where
        F: for<'a> Fn(
                &'a mut dyn IHttpContext,
            ) -> std::pin::Pin<
                Box<dyn std::future::Future<Output = Result<()>> + Send + 'a>,
            > + Send
            + Sync
            + 'static,
    {
        Self {
            handler: Box::new(f),
        }
    }
}

/// Endpoint that serves a static JSON payload.
///
/// Used for built-in endpoints like `/openapi.json`.
pub struct StaticJsonEndpoint {
    pub body: Vec<u8>,
}

#[async_trait::async_trait]
impl IEndpoint for StaticJsonEndpoint {
    async fn handle(&self, ctx: &mut dyn IHttpContext) -> Result<()> {
        ctx.response_mut().set_status(200);
        ctx.response_mut()
            .set_header("content-type", "application/json");
        ctx.response_mut().write_bytes(self.body.clone()).await
    }
}

/// Endpoint that serves a static HTML payload.
///
/// Used for built-in endpoints like `/api/docs`.
pub struct StaticHtmlEndpoint {
    pub body: &'static str,
}

#[async_trait::async_trait]
impl IEndpoint for StaticHtmlEndpoint {
    async fn handle(&self, ctx: &mut dyn IHttpContext) -> Result<()> {
        ctx.response_mut().set_status(200);
        ctx.response_mut()
            .set_header("content-type", "text/html; charset=utf-8");
        ctx.response_mut()
            .write_bytes(self.body.as_bytes().to_vec())
            .await
    }
}
