[package]
name = "lrwf-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "LRWF procedural macros: #[controller], #[endpoint], #[HttpGet], #[FromBody], lrwf::request!"

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
