[package]
name = "rust-webapp-spa"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "rust-webapp SPA: static file serving middleware"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
rust-webapp-core.workspace = true
async-trait.workspace = true
tokio.workspace = true
