[package]
name = "rust-webx"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "rust-webx — A Rust WebApi framework inspired by ASP.NET Core"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true

[dependencies]
rust-webx-core.workspace = true
rust-webx-host.workspace = true
rust-webx-macros.workspace = true
rust-webx-spa.workspace = true
rust-webx-openapi.workspace = true
rust-dix.workspace = true
rust-dix-macros.workspace = true
async-trait.workspace = true
tokio.workspace = true
hyper.workspace = true
serde.workspace = true
serde_json.workspace = true
inventory.workspace = true
jsonwebtoken.workspace = true
