// rust-webx-spa — SPA static file serving middleware.

mod embed;
mod spa;

pub use embed::{EmbeddedAsset, EmbeddedAssets};
pub use spa::{SpaMiddleware, SpaSource, EMBED_ENV};

/// Re-exported so build-script-generated code can register a table without
/// depending on `inventory` directly.
pub use inventory;

/// Include the asset table generated by `rust_webx_build::embed_assets`.
///
/// Needs no arguments: the table is already written into `OUT_DIR` by the build
/// script. Invoke it once per binary, at module level:
///
/// ```ignore
/// rust_webx::spa::embed_assets!();
/// ```
///
/// It expands to `include!(concat!(env!("OUT_DIR"), "/rust_webx_embedded_assets.rs"))`,
/// which registers the table with [`EmbeddedAssets`], so
/// `Host::builder().embed()` can find it.
#[macro_export]
macro_rules! embed_assets {
    () => {
        // The file name is `rust_webx_build::GENERATED_FILE`. It is spelled out
        // here because a build dependency cannot be reached from this crate.
        include!(concat!(env!("OUT_DIR"), "/rust_webx_embedded_assets.rs"));
    };
}
