[package]
name = "docbit-handlers"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
docbit-contracts.workspace = true
docbit-domain.workspace = true
rust-ef.workspace = true
rust-webx.workspace = true
rust-dix.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
jsonwebtoken.workspace = true
bcrypt = "0.16"
tracing.workspace = true
inventory.workspace = true

[dev-dependencies]
rust-ef-sqlite.workspace = true
tempfile = "3"
